Sprint 18
volk-r/TravelSchedule pull request #1
Opened 2024-11-07 19:12 UTC by volk-r

OpenAPI Generator for Network layer

2024-11-08 11:57 UTC, protos17 requested changes

2024-11-08 11:57 UTC, protos17 commented on TravelSchedule/Services/NearestStationsService.swift
> + */
Лишний закомментированный код рекомендую удалять. Проверку работоспособности вызовов рекомендую реализовать в тестах

2024-11-08 11:57 UTC, protos17 commented on TravelSchedule/AppSettings/AppConstants.swift
> +    static let ApiScheduleKey = "481665d9-4609-4b54-ac58-e304d876c93b"
Названия переменных принято указывать с маленькой буквы

2024-11-12 04:35 UTC, volk-r commented on TravelSchedule/AppSettings/AppConstants.swift
> +    static let ApiScheduleKey = "481665d9-4609-4b54-ac58-e304d876c93b"
fixed

2024-11-12 04:35 UTC, volk-r commented on TravelSchedule/Services/NearestStationsService.swift
> + */
done

2024-11-12 15:47 UTC, protos17 approved these changes

2024-11-12 15:47 UTC, protos17 commented on TravelSchedule/TravelScheduleApp.swift
> +    func searchRoutes(from origin: String, to destination: String) async throws -> SearchResponse {
Если сами эти вызовы находятся в тестах, то можно было не указывать эти вызовы здесь, а в самих тестах создать экземпляры сервисов и вызвать их методы. Но так тоже можно оставить

2024-11-13 03:57 UTC, merged